name: 'first container action'
description 'inital container'
author: 'Peter Muniz'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'User'
    
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
